In [2]:
!ls

2d_from_3D.numbers      flame_fit.py            read.py
__pycache__             input                   readme.md
align_flame_to_input.py output                  sanity.jpg
crop_align.py           pi                      scripts
dense2d.py              pw.npy                  select_camera.ipynb
exp.ipynb               pw_flame.npy            select_img_dense2d.py


In [4]:
! python read.py

--------
[[2.02089843e+04 0.00000000e+00 1.29006482e+03 0.00000000e+00]
 [0.00000000e+00 2.02089843e+04 4.37122877e+02 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 1.00000000e+00]]
---------
**************** 1.jpg
[[ 1.  0.  0.  0.]
 [ 0. -1.  0.  0.]
 [ 0.  0. -1.  0.]
 [ 0.  0.  0.  1.]]
-7199171.03644927 2987.84756375747 -21194.728698070547
-102.73422633995507 10502372.623744493 21573.13072969038
**************** 8.jpg
[[ 0.77793769  0.01780174  0.62808921 -1.84972201]
 [-0.0186564  -0.99850347  0.05140768 -0.19460667]
 [ 0.6280644  -0.05170986 -0.77644137 -0.74532109]
 [ 0.          0.          0.          1.        ]]
-332282342.8194761 96466266.82432579 -141622.90670234722
-75890909.76708086 706292122.9359493 144750.4960851526
**************** 10.jpg
[[ 0.94836693  0.06953257 -0.30945983  0.9239882 ]
 [ 0.02308017 -0.98821667 -0.15131132  0.47745942]
 [-0.31633443  0.13635627 -0.93879683 -0.13737638]

#### Plot the landmarks on image and check qualilty

In [76]:
import numpy as np
lmks = np.load('./output/flame_2d/122_3/pi/40.npy')
print(len(lmks))
print(lmks)

14999
[[ 2257.98209542  1849.62576005]
 [ 2298.79188917  1858.45949386]
 [ 2308.05958493  1843.24400361]
 ...
 [-6948.09450548 11421.01439633]
 [-6964.53579031 11421.08407502]
 [-7488.52217531 11644.40101726]]


In [79]:
import cv2
image = cv2.imread('./input/122_3/40.jpg')
for point in lmks:
    point = [int(point[0]), int(point[1])]
    image = cv2.circle(image, point, radius=3, color=(0, 255, 0), thickness=-1)

cv2.imwrite('sanity.jpg', image)

True

In [8]:
'''indices_file = "../../../2D_Landmarks/DAD-3DHeads/model_training/model/static/face_keypoints/ids1.npy"
indices = np.load(indices_file)
points = []
points.extend(np.take(lmks, indices, axis=0))

image = cv2.imread('./input/122_3/44.jpg')
for point in points:
    point = [int(point[0]), int(point[1])]
    image = cv2.circle(image, point, radius=3, color=(0, 255, 0), thickness=-1)

cv2.imwrite('./data/flame_2d/44.jpg', image)'''

'indices_file = "../../../2D_Landmarks/DAD-3DHeads/model_training/model/static/face_keypoints/ids1.npy"\nindices = np.load(indices_file)\npoints = []\npoints.extend(np.take(lmks, indices, axis=0))\n\nimage = cv2.imread(\'./input/122_3/44.jpg\')\nfor point in points:\n    point = [int(point[0]), int(point[1])]\n    image = cv2.circle(image, point, radius=3, color=(0, 255, 0), thickness=-1)\n\ncv2.imwrite(\'./data/flame_2d/44.jpg\', image)'

#### select 1797 from flame 2d and save

In [20]:
# select 1797 from flame 2d and save
import numpy as np
indices_file = "../../../2D_Landmarks/DAD-3DHeads/model_training/model/static/face_keypoints/ids1.npy"
indices = np.load(indices_file)
points = []
lmks = np.load('./output/flame_2d/19_3/pi/8.npy')
points.extend(np.take(lmks, indices, axis=0))
points = np.array(points)
'''print(points)
image = cv2.imread('./input/122_3/40.jpg')
for point in points:
    point = [int(point[0]), int(point[1])]
    image = cv2.circle(image, point, radius=3, color=(0, 255, 0), thickness=-1)

cv2.imwrite('sanity.jpg', image)'''

"print(points)\nimage = cv2.imread('./input/122_3/40.jpg')\nfor point in points:\n    point = [int(point[0]), int(point[1])]\n    image = cv2.circle(image, point, radius=3, color=(0, 255, 0), thickness=-1)\n\ncv2.imwrite('sanity.jpg', image)"

In [21]:
np.save('./output/flame_2d/19_3/8.npy', points)

In [22]:
import cv2
points = np.load('./output/flame_2d/19_3/8.npy')
image = cv2.imread('./input/3_cameras/19/8.jpg')
print(points)
for point in points:
    point = [int(point[0]), int(point[1])]
    image = cv2.circle(image, point, radius=3, color=(0, 255, 0), thickness=-1)

cv2.imwrite('./output/flame_2d/19_3/8.jpg', image)

[[2612.95104224  624.14313183]
 [2625.21312502  644.44690374]
 [2651.39207294  708.38905802]
 ...
 [2677.9478186  1663.84640885]
 [2712.34744229 1922.66817851]
 [2692.08325717 1954.69006197]]


True

#### Draw lmks for GT

In [40]:
gt_points = np.load('./output/GT/19/8.npy')
image = cv2.imread('./input/3_cameras/19/8.jpg')
for point in gt_points:
    point = [int(point[0]), int(point[1])]
    image = cv2.circle(image, point, radius=3, color=(0, 255, 0), thickness=-1)

cv2.imwrite('./output/GT/19/8.jpg', image)

True

#### Calculate error for flame_2d and dad-net wrt to GT

In [25]:
def calculate_error(x,y, pred_x, pred_y):
    #norm_factor = (np.sqrt(np.square(x[36]-x[45]) + np.square(y[36]-y[47])))*len(x)
    ret = 0
    for i in range(len(x)):
        ret += np.sqrt(np.square(pred_x[i]-x[i]) + np.square(pred_y[i]-y[i]))
    return ret/len(x)

In [31]:
gt_lmks = np.load('./output/GT/19/1.npy')
flame_2d_lmks = np.load('./output/flame_2d/19_3/1.npy')
dadnet_2d_lmks = np.load('./output/dadNet_2d/19/1.npy')

In [32]:
flame_2d_error = calculate_error(gt_lmks[:,0], gt_lmks[:,1],flame_2d_lmks[:,0], flame_2d_lmks[:,1])
dadnet_2d_error = calculate_error(gt_lmks[:,0], gt_lmks[:,1],dadnet_2d_lmks[:,0], dadnet_2d_lmks[:,1])

In [33]:
print('flame 2D error for 40.jpg : ', flame_2d_error)
print('dadnet 2D error for 40.jpg : ', dadnet_2d_error)

flame 2D error for 40.jpg :  61.67133121354123
dadnet 2D error for 40.jpg :  74.04490549728874


In [34]:
gt_lmks = np.load('./output/GT/19/10.npy')
flame_2d_lmks = np.load('./output/flame_2d/19_3/10.npy')
dadnet_2d_lmks = np.load('./output/dadNet_2d/19/10.npy')

In [35]:
flame_2d_error = calculate_error(gt_lmks[:,0], gt_lmks[:,1],flame_2d_lmks[:,0], flame_2d_lmks[:,1])
dadnet_2d_error = calculate_error(gt_lmks[:,0], gt_lmks[:,1],dadnet_2d_lmks[:,0], dadnet_2d_lmks[:,1])

In [36]:
print('flame 2D error for 44.jpg : ', flame_2d_error)
print('dadnet 2D error for 44.jpg : ', dadnet_2d_error)

flame 2D error for 44.jpg :  63.05048460262335
dadnet 2D error for 44.jpg :  66.58625450021873


In [37]:
gt_lmks = np.load('./output/GT/19/8.npy')
flame_2d_lmks = np.load('./output/flame_2d/19_3/8.npy')
dadnet_2d_lmks = np.load('./output/dadNet_2d/19/8.npy')

In [38]:
flame_2d_error = calculate_error(gt_lmks[:,0], gt_lmks[:,1],flame_2d_lmks[:,0], flame_2d_lmks[:,1])
dadnet_2d_error = calculate_error(gt_lmks[:,0], gt_lmks[:,1],dadnet_2d_lmks[:,0], dadnet_2d_lmks[:,1])

In [39]:
print('flame 2D error for 44.jpg : ', flame_2d_error)
print('dadnet 2D error for 44.jpg : ', dadnet_2d_error)

flame 2D error for 44.jpg :  57.909768157682116
dadnet 2D error for 44.jpg :  61.36817670267865
